/**                                           
 * @file    build_info.h                      
 * @brief   Git tag and commit information    
 * @warning DO NOT EDIT!                      
 *          Generated by CreateBuildInfo.bat  
 */                                           
                                              
#ifndef BUILD_INFO_H                          
#define BUILD_INFO_H                          
                                              
#define BUILD_DATE    "2020/03/31"          
                                              
#define BUILD_TIME    "16:50:30"          
                                              
#define BUILD_INFO    "5d94-dirty"          
                                              
#define BUILD_BRANCH  "update-vendor"        
                                              
#endif /* BUILD_INFO_H */                     
                                              
