/**                                                                      
 * @file    build_info.h                                                 
 * @brief   Git tag and commit information                               
 * @warning DO NOT EDIT!                                                 
 *          Generated by CreateBuildInfo.bat                             
 */                                                                      
                                                                         
#ifndef BUILD_INFO_H                                                     
#define BUILD_INFO_H                                                     
                                                                         
#define BUILD_DATE    "2018-10-14"                                     
                                                                         
#define BUILD_TIME    "23:50:28"                                     
                                                                         
#define BUILD_INFO    "c99e-dirty"                                     
                                                                         
#define BUILD_BRANCH  "master"                                   
                                                                         
#endif /* BUILD_INFO_H */                                                
                                                                         
