/**                                           
 * @file    build_info.h                      
 * @brief   Git tag and commit information    
 * @warning DO NOT EDIT!                      
 *          Generated by CreateBuildInfo.bat  
 */                                           
                                              
#ifndef BUILD_INFO_H                          
#define BUILD_INFO_H                          
                                              
#define BUILD_DATE    "2020/01/04"          
                                              
#define BUILD_TIME    "22:46:25"          
                                              
#define BUILD_INFO    "0d5b-dirty"          
                                              
#define BUILD_BRANCH  "master"        
                                              
#endif /* BUILD_INFO_H */                     
                                              
