/**                                           
 * @file    build_info.h                      
 * @brief   Git tag and commit information    
 * @warning DO NOT EDIT!                      
 *          Generated by CreateBuildInfo.bat  
 */                                           
                                              
#ifndef BUILD_INFO_H                          
#define BUILD_INFO_H                          
                                              
#define BUILD_DATE    "2020/02/14"          
                                              
#define BUILD_TIME    "14:52:56"          
                                              
#define BUILD_INFO    "1195-dirty"          
                                              
#define BUILD_BRANCH  "master"        
                                              
#endif /* BUILD_INFO_H */                     
                                              
