/**                                                                      
 * @file    build_info.h                                                 
 * @brief   Git tag and commit information                               
 * @warning DO NOT EDIT!                                                 
 *          Generated by CreateBuildInfo.bat                             
 */                                                                      
                                                                         
#ifndef BUILD_INFO_H                                                     
#define BUILD_INFO_H                                                     
                                                                         
#define BUILD_DATE    "2018-05-19"                                     
                                                                         
#define BUILD_TIME    "15:05:18"                                     
                                                                         
#define BUILD_INFO    "587f-dirty"                                     
                                                                         
#define BUILD_BRANCH  "master"                                   
                                                                         
#endif /* BUILD_INFO_H */                                                
                                                                         
