/**                                                                      
 * @file    build_info.h                                                 
 * @brief   Git tag and commit information                               
 * @warning DO NOT EDIT!                                                 
 *          Generated by CreateBuildInfo.bat                             
 */                                                                      
                                                                         
#ifndef BUILD_INFO_H                                                     
#define BUILD_INFO_H                                                     
                                                                         
#define BUILD_DATE    "2018-09-26"                                     
                                                                         
#define BUILD_TIME    "23:38:01"                                     
                                                                         
#define BUILD_INFO    "2753-dirty"                                     
                                                                         
#define BUILD_BRANCH  "master"                                   
                                                                         
#endif /* BUILD_INFO_H */                                                
                                                                         
