enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
    spec: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
npmScopes:
  electricui:
    npmRegistryServer: 'https://registry.eui.io/'
prebuildHostMirrorTemplate: '{mirror_url}/{scopeWithAtAndSlash}{name}-v{version}-{runtime}-v{abi}-{platform}{libc}-{arch}.tar.gz'
prebuildHostMirrorUrl: 'https://registry.eui.io/prebuilds'
packageExtensions:
  chokidar@*:
    dependencies:
      fsevents: 2.1.2
  debug@*:
    dependencies:
      supports-color: 7.1.0
