name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'

      - name: Generate version metadata
        run: |
          cd firmware
          ./CreateBuildInfo.sh

      - name: Configure
        run: |
          cd firmware
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        run: |
          cd firmware/build
          make

      # Upload the binaries as artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: built-binaries
          path: |
            firmware/build/*.bin
          retention-days: 7
          if-no-files-found: ignore

      - name: Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            firmware/build/*.bin
